#!/usr/bin/env python3
"""community_tribute.py — Generate community tribute letters using local king AI.

Zero Claude tokens. Reads feed data from reports/civic/, queries king-jrcsl
(Jimmy's doctrine + Christ-aloha voice) to generate a tribute, saves result.

Usage:
  python tools/kilo-aupuni/community_tribute.py --subject "Sam Small" --feed maui_causes
  python tools/kilo-aupuni/community_tribute.py --subject "Sam Small" --draft  # save draft only
  python tools/kilo-aupuni/community_tribute.py --subject "Sam Small" --wp     # post to WP draft

The output is a DRAFT for Jimmy's review. Never auto-publishes.
"""
import os, sys, json, subprocess, argparse
from datetime import datetime

HERE   = os.path.dirname(os.path.abspath(__file__))
ROOT   = os.path.dirname(os.path.dirname(HERE))
CIVIC  = os.path.join(ROOT, "reports", "civic")
OUT    = os.path.join(ROOT, "docs", "community")
DISPATCH = os.path.join(ROOT, "app", "server", "dispatch.py")
PY = sys.executable

OLLAMA_MODEL = "king-jrcsl"  # Jimmy's doctrine + EI + Christ-aloha voice
OLLAMA_FALLBACK = "king-civic"  # fallback if jrcsl not available


def ollama_query(model, prompt, system=None, timeout=120):
    """Call Ollama locally. Returns response text or None."""
    cmd = ["ollama", "run", model]
    full_prompt = f"{system}\n\n{prompt}" if system else prompt
    try:
        r = subprocess.run(cmd, input=full_prompt, capture_output=True,
                           text=True, timeout=timeout, encoding="utf-8")
        if r.returncode == 0 and r.stdout.strip():
            return r.stdout.strip()
        # Try fallback
        if model != OLLAMA_FALLBACK:
            return ollama_query(OLLAMA_FALLBACK, prompt, system, timeout)
        return None
    except Exception as e:
        print(f"[tribute] Ollama error: {e}", flush=True)
        return None


def load_latest_feed(feed_name):
    """Load the most recent feed JSON from reports/civic/."""
    import glob as _glob
    pattern = os.path.join(CIVIC, f"{feed_name}_*.json")
    files = sorted(_glob.glob(pattern), reverse=True)
    if not files:
        return None
    with open(files[0], encoding="utf-8") as f:
        return json.load(f)


def build_context(feed_data, subject):
    """Build a compact context string from feed data for the AI prompt."""
    if not feed_data:
        return f"Subject: {subject}\n(No feed data available)"
    posts = feed_data.get("posts", [])
    lines = [f"Community servant: {subject}",
             f"Organization: {feed_data.get('source', '')} — {feed_data.get('source_url', '')}",
             f"Recent work ({len(posts)} items):"]
    for p in posts[:8]:
        icon = "▶" if p.get("type") == "video" else "✍"
        lines.append(f"  {icon} [{p.get('date','')[:10]}] {p.get('title','')[:80]}")
    return "\n".join(lines)


def generate_tribute(subject, feed_name="maui_causes"):
    feed_data = load_latest_feed(feed_name)
    context = build_context(feed_data, subject)

    system = (
        "You are the voice of Jimmy Langford (elementLOTUS, 12sgi). "
        "Your voice is Christ-aloha: warm, humble, direct, grateful, truth-grounded. "
        "You write as a Hawaiian sovereign rights artist who sees community service as sacred. "
        "You never boast. You witness clearly and offer gratitude plainly. "
        "You reference specific work by name. You connect civic labor to spiritual aloha. "
        "Keep it under 600 words. No hashtags. No hollow praise. Real witness."
    )

    prompt = (
        f"Write a personal tribute letter from Jimmy Langford to {subject}. "
        f"This is a spiritual thank-you — an offering of gratitude for their civic service to Maui. "
        f"Reference their specific work listed below. "
        f"Connect their labor to the principle of aloha as love in action. "
        f"Mention PULSE (Jimmy's song at Node 54 — Universal Synergy) as the heartbeat metaphor. "
        f"Close with 'Me ke aloha pumehana, Jimmy Langford / elementLOTUS'.\n\n"
        f"CONTEXT:\n{context}"
    )

    print(f"[tribute] Querying {OLLAMA_MODEL}...", flush=True)
    result = ollama_query(OLLAMA_MODEL, prompt, system)
    if not result:
        print("[tribute] Local AI unavailable — Ollama not running or model not found.", flush=True)
        return None

    return result


def save_draft(subject, text):
    os.makedirs(OUT, exist_ok=True)
    slug = subject.lower().replace(" ", "_")
    today = datetime.now().strftime("%Y-%m-%d")
    outfile = os.path.join(OUT, f"tribute_{slug}_{today}.md")
    with open(outfile, "w", encoding="utf-8") as f:
        f.write(f"# Tribute: {subject}\n")
        f.write(f"# Generated by king-jrcsl (local AI) · {today}\n")
        f.write(f"# DRAFT — Jimmy review before publish\n\n")
        f.write(text)
    print(f"[tribute] Draft saved → {outfile}", flush=True)
    return outfile


def dispatch_log(msg):
    if os.path.exists(DISPATCH):
        subprocess.run([PY, "-X", "utf8", DISPATCH, ROOT,
                        "--log-event", msg, "--source", "audit-quad-os"],
                       capture_output=True, cwd=ROOT)


def main():
    ap = argparse.ArgumentParser(description="Generate community tribute with local king AI")
    ap.add_argument("--subject", default="Sam Small", help="Person to tribute")
    ap.add_argument("--feed",    default="maui_causes", help="Feed name in reports/civic/")
    ap.add_argument("--draft",   action="store_true", help="Save draft only (default)")
    ap.add_argument("--wp",      action="store_true", help="Also post to WordPress as private draft")
    args = ap.parse_args()

    print(f"[tribute] Generating tribute for {args.subject} using local king AI (zero Claude tokens)", flush=True)
    text = generate_tribute(args.subject, args.feed)
    if not text:
        print("[tribute] Generation failed — check Ollama is running: ollama list", flush=True)
        return 1

    draft_path = save_draft(args.subject, text)
    print("\n" + "="*60)
    print(text[:800])
    print("="*60 + "\n")

    dispatch_log(
        f"SHIPPED: community_tribute.py generated '{args.subject}' tribute via king-jrcsl "
        f"(zero Claude tokens) → {os.path.basename(draft_path)}"
    )

    if args.wp:
        print("[tribute] WordPress posting: use wpcom-mcp-content-authoring to create private draft", flush=True)
        print(f"[tribute] Title: 'On the Pulse of a Community — A Letter to {args.subject}'")
        print(f"[tribute] Content ready at: {draft_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
