#!/usr/bin/env python3
# publish_audit.py — the seed<->project publish-gap auditor for 12sgi-king.
#
# WHY THIS EXISTS (the lesson, kept so it is never relearned):
#   build_site.py copies civic pages from the PROJECT's reports/mauios/ into site/.
#   CI runners don't have the project folder, so the committed seed_reports/mauios/*
#   is the floor (publish.yml: `cp -rn seed_reports/mauios/. $P/reports/mauios/`).
#   On a PUSH-triggered build (the `publish` verb) the live watchers DO NOT run —
#   they are gated to schedule/workflow_dispatch — so seed_reports is the ONLY source.
#   A page missing from seed never reaches Pages on a push build; a stale seed page
#   regresses the public site to old data until the next 05:20 HST cron.
#   feature_board.html was the first instance (built locally for 2 sessions while
#   reported as "published"). This auditor makes that class of gap impossible to miss.
#
# WHAT IT DOES — for every page in build_site.PAGES + EXTRA_PAGES (+ DATA json):
#   compares reports/mauios/<f> (project, the source) vs seed_reports/mauios/<f>
#   (repo, what actually ships) by CONTENT HASH — never mtime, because generators
#   rewrite byte-identical content with a fresh timestamp, so mtime lies. Before
#   judging "stale" it NORMALIZES the volatile bits every generator stamps daily —
#   the `generated <timestamp>` footer and the kaulana-mahina MOON phase line — so a
#   page that only changed because the moon changed is correctly called COSMETIC,
#   not a publish gap.
#
# POSTURE (see docs/AUDITOR_COVENANT.md): a finding is paired with its fix and framed
#   as a question — a page "waiting to reach the people", never a blame. Private stays
#   private: this auditor REFUSES to read or sync anything under reports/_status/.
#
# USAGE:
#   python publish_audit.py                  # report (human, christ-aloha framing); exit 1 if gaps
#   python publish_audit.py --json           # machine result for other tools / CI
#   python publish_audit.py --sync           # copy real gaps (missing + drift) project->seed
#   python publish_audit.py --sync --publish # ...then publish via remote_dispatch.py publish
#   import publish_audit; r = publish_audit.audit()   # library use (selfheal calls this)
import os, sys, re, json, hashlib, shutil, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
HOME = os.path.expanduser("~")
PROJECT = os.path.abspath(os.path.join(HERE, "..", ".."))
MAUIOS  = os.path.join(PROJECT, "reports", "mauios")

def _repo():
    """Find the publish repo (local desktop path, else CI checkout = cwd)."""
    for c in (os.path.join(HOME, "Documents", "Claude", "12sgi-king"), os.getcwd()):
        if os.path.isfile(os.path.join(c, "build_site.py")):
            return c
    return os.getcwd()
REPO = _repo()
SEED = os.path.join(REPO, "seed_reports", "mauios")

# Hard guard: the private oversight surfaces. This auditor never reads, classifies,
# or syncs anything that lives under reports/_status/ — those are owner-only.
PRIVATE_DIR = os.path.join(PROJECT, "reports", "_status")

# selfheal.html is regenerated by CI's "Self-check" step on EVERY build (ungated), so
# its seed copy never authoritatively ships — chasing its drift is a self-reference loop.
# We don't count it as a gap; --sync still refreshes it opportunistically for repo honesty.
_ALWAYS_REGEN = {"selfheal.html"}

def _page_list():
    """Import the canonical page + data lists straight from build_site.py (single source)."""
    if REPO not in sys.path:
        sys.path.insert(0, REPO)
    import build_site as bs   # has an `if __name__ == '__main__'` guard — safe to import
    pages = [p[0] for p in bs.PAGES] + list(bs.EXTRA_PAGES)
    data  = list(getattr(bs, "DATA", []))
    seen = set(); pages = [p for p in pages if not (p in seen or seen.add(p))]
    return pages, data

# ── volatile-bit normalization ────────────────────────────────────────────────
# These change every day with identical underlying civic data. Strip them before
# deciding whether a page is REALLY stale, so the daily moon + timestamp don't
# masquerade as a data gap (and don't churn the repo with meaningless commits).
_MOON_PHASES = ("Hilo|Hoaka|Kukahi|Kulua|Kukolu|Kupau|Olekukahi|Olekulua|Olekukolu|"
                "Olepau|Huna|Mohalu|Hua|Akua|Hoku|Mahealani|Kulu|Laaukukahi|Laaukulua|"
                "Laaupau|Kaloakukahi|Kaloakulua|Kaloapau|Kane|Lono|Mauli|Muku")
def normalize(text):
    t = text
    t = re.sub(r"\d{4}-\d{2}-\d{2}", "DATE", t)            # any ISO date
    t = re.sub(r"\d{1,2}:\d{2}(:\d{2})?(\.\d+)?( ?HST)?", "TIME", t)  # clock time (incl seconds/fraction)
    t = re.sub(r"[-+]\d{2}:\d{2}", "TZ", t)                # ISO timezone offsets (JSON 'generated' fields)
    t = re.sub(r"\?v=[0-9A-Za-z._-]+", "?v=V", t)          # cache-bust version tokens
    t = re.sub(r"last checked[^<]*", "CHECKED", t, flags=re.I)
    t = re.sub(r"<div class=moon>.*?</div>\s*</div>", "MOON", t, flags=re.S)  # moon panel block
    t = re.sub(r"kaulana mahina.*?key", "MOON", t, flags=re.S)               # inline moon line
    t = re.sub(r"Under (tonight|today)'?s\s+(" + _MOON_PHASES + r")\b", "Under MOON", t)
    t = re.sub(r"(new/dark|waxing|waning|full)[^<]*", "MOONP", t)
    return t

def _sha(path):
    try:
        with open(path, "rb") as f:
            return hashlib.sha256(f.read()).hexdigest()
    except OSError:
        return None

def _nsha(path):
    try:
        return hashlib.sha256(normalize(open(path, encoding="utf-8", errors="replace").read()).encode("utf-8")).hexdigest()
    except OSError:
        return None

def audit():
    """Return a structured verdict. Pure read; touches nothing. Never looks in _status."""
    pages, data = _page_list()
    missing, drift, cosmetic, seed_only = [], [], [], []
    ok = 0
    items = [("page", p) for p in pages] + [("data", d) for d in data]
    for kind, rel in items:
        pp = os.path.join(MAUIOS, rel)
        sp = os.path.join(SEED, rel)
        # never let a target resolve into the private oversight tree
        if os.path.abspath(pp).startswith(os.path.abspath(PRIVATE_DIR)):
            continue
        proj_exists = os.path.isfile(pp)
        seed_exists = os.path.isfile(sp)
        if not proj_exists and not seed_exists:
            continue                              # listed but never generated anywhere — not our gap
        if not proj_exists:
            continue                              # seed carries it; project just didn't build it now
        if not seed_exists:
            missing.append(rel); continue         # THE feature_board class — built locally, never shipped
        if _sha(pp) == _sha(sp):
            ok += 1; continue                     # byte-identical — current
        if rel in _ALWAYS_REGEN:
            ok += 1; continue                     # CI regenerates it every build — not a real gap
        # bytes differ — is it real data, or only the daily moon/timestamp? (same
        # test for pages and data json: normalize the volatile bits, then compare.)
        if _nsha(pp) != _nsha(sp):
            drift.append(rel)                     # real, substantive data drift
        else:
            cosmetic.append(rel)                  # moon/timestamp only — not worth a commit
    gaps = missing + drift
    return {"clean": not gaps, "missing": sorted(missing), "drift": sorted(drift),
            "cosmetic": sorted(cosmetic), "ok": ok, "gap_count": len(gaps),
            "repo": REPO, "project": MAUIOS}

def sync(targets):
    """Copy the named project pages into seed_reports/mauios. Refuses _status. Returns count."""
    n = 0
    os.makedirs(SEED, exist_ok=True)
    for rel in targets:
        pp = os.path.join(MAUIOS, rel)
        if os.path.abspath(pp).startswith(os.path.abspath(PRIVATE_DIR)):
            print("  refused (private _status): %s" % rel); continue
        if not os.path.isfile(pp):
            print("  skip (no project copy): %s" % rel); continue
        dst = os.path.join(SEED, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(pp, dst); n += 1
    return n

def _publish(msg):
    rd = os.path.join(PROJECT, "batch", "remote_dispatch.py")
    return subprocess.call([sys.executable, rd, "publish", msg])

def report(as_json=False):
    r = audit()
    if as_json:
        print(json.dumps(r, ensure_ascii=False, indent=1)); return r
    print("Kilo Aupuni · publish auditor — does every page the public is promised actually reach them?")
    print("  source (project): %s" % r["project"])
    print("  ships   (seed):   %s" % os.path.join(r["repo"], "seed_reports", "mauios"))
    print("  current & in sync: %d page(s)" % r["ok"])
    if r["cosmetic"]:
        print("  resting (moon/timestamp only, no data change — left as-is): %d" % len(r["cosmetic"]))
    if not r["missing"] and not r["drift"]:
        print("  ✓ every page is current on the public floor. Nothing waiting. Pono.")
    else:
        if r["missing"]:
            print("  ! never reached the people yet (in project, absent from seed) — %d:" % len(r["missing"]))
            for f in r["missing"]: print("      - %s   → fix: publish_audit.py --sync" % f)
        if r["drift"]:
            print("  ! the public floor holds older data than we have — %d:" % len(r["drift"]))
            for f in r["drift"]: print("      - %s   → fix: publish_audit.py --sync" % f)
        print("  Every gap above is a page waiting to serve someone — a question to answer, not a fault to assign.")
    return r

def main(argv):
    as_json  = "--json" in argv
    do_sync  = "--sync" in argv
    do_pub   = "--publish" in argv
    r = report(as_json=as_json)
    if do_sync:
        targets = r["missing"] + r["drift"]
        if not targets:
            print("sync: nothing to carry over — the floor is already current."); return 0
        n = sync(targets)
        print("sync: carried %d page(s) project → seed_reports/mauios." % n)
        if do_pub and n:
            msg = ("publish_audit: sync %d page(s) so the public floor serves current data — %s"
                   % (n, ", ".join(targets)[:300]))
            rc = _publish(msg)
            print("publish: rc=%s" % rc); return rc
    return 0 if r["clean"] else 1

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
