# -*- coding: utf-8 -*-
"""tenant_directory.py — the govOS tenant directory ("every page") in the FRESH YALE BLUE register.

Jimmy 2026-07-08 ("this is the new look man", artifact govOS-civic-fresh-yale-blue): the committed
dark-navy civic register — glass cards, Yale blue (#00356b deep / #2f74d0 / #5a97e6), gold accent
(#e3ad33), light ink (#eaf2fc) on deep navy (#081420) with radial glows, system faces (iOS-safe, no
font-CDN). This REPLACES the orphaned black-box directory (unreadable dark-on-dark).

SINGLE SOURCE OF TRUTH, WIRED (2026-07-09 heal-audit fix): the PUBLISHED site/maui.html + king-local
copy are generated by 12sgi-king/build_site.py's build_maui_nav_page(), which imports page_html() from
THIS module and supplies its OWN existence-filtered MAUI_NAV_GROUPS data (build_site.py knows which
pages actually exist in its SITE tree; this module doesn't, and previously shipping a hardcoded/unfiltered
SECTIONS list here risked linking dead pages or drifting from the real directory). That single generator
call is the ONLY writer of site/maui.html in the standing publish pipeline — running THIS script standalone
only refreshes reports/mauios/maui.html, a private ad-hoc copy; it does NOT touch the published page.

page_html() renders NO <nav> element — build_site.py's inject_nav() supplies the one standing govOS nav
bar (already dark-navy) right after <body>, so there is exactly one nav per page, never two stacked/
colliding navs (the exact failure class that made tenant_pages.py's output unreadable).

  python tools/kilo-aupuni/tenant_directory.py            # ad-hoc: refresh reports/mauios/maui.html only
"""
import os, html

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "reports", "mauios")

def esc(s): return html.escape(str(s))

# Fallback/standalone directory data (used only when this script runs ad-hoc, NOT for the published page —
# see module docstring). Kept in sync manually with build_site.py's MAUI_NAV_GROUPS; that file is authoritative.
SECTIONS = [
 ("Start here", [("Maui County overview", "tenant_hi-maui.html"), ("County dashboard", "county_dashboard.html"),
                 ("Aloha ʻĀina", "aloha_aina.html")]),
 ("Who governs", [("Officials scorecard", "officials_scorecard.html"), ("Officials", "officials_maui.html"),
                  ("Audit by representative", "rep_audit.html"), ("The donor bloc", "donor_bloc.html"),
                  ("Ka Leo — the louder voice", "ka_leo_voice.html"), ("All departments", "departments_maui.html")]),
 ("Departments", [("Council", "dept_council_maui.html"), ("Mayor", "dept_mayor_maui.html"),
                  ("Management", "dept_management_maui.html"), ("Finance", "dept_finance_maui.html"),
                  ("Public Works", "dept_public_works_maui.html"), ("Water Supply", "dept_water_maui.html"),
                  ("Planning", "dept_planning_maui.html"), ("Environmental Mgmt", "dept_environmental_maui.html"),
                  ("Fire & Public Safety", "dept_fire_maui.html"), ("Police", "dept_police_maui.html"),
                  ("Prosecuting Attorney", "dept_prosecutor_maui.html"), ("Parks & Rec", "dept_parks_maui.html"),
                  ("Housing & Human Concerns", "dept_housing_maui.html"), ("Agriculture", "dept_agriculture_maui.html"),
                  ("Transportation", "dept_transportation_maui.html"), ("Liquor Control", "dept_liquor_maui.html"),
                  ("Personnel Services", "dept_personnel_maui.html"), ("Corporation Counsel", "dept_corp_counsel_maui.html")]),
 ("Follow the money", [("Money behind officials", "money_behind_officials.html"), ("Campaign money", "money_maui.html"),
                       ("Real-estate money", "realestate_maui.html"), ("Contract awards", "maui_contract_awards.html"),
                       ("Federal dollars", "federal_money.html")]),
 ("Money × votes", [("Contracts × donors", "contracts_x_donors.html"), ("Who testifies × money", "testifiers_maui.html"),
                    ("Testimony effect map", "testimony_effect_map.html"), ("Lobby + money", "lobby_money_watch.html"),
                    ("Pairs that no longer answer", "parity_check.html")]),
 ("Agendas & meetings", [("Upcoming agendas", "agendas_maui.html"), ("Meetings calendar", "meetings_maui.html"),
                         ("Meeting archive", "archive_maui.html"), ("Sunshine Law watch", "sunshine_maui.html")]),
 ("The record", [("Council votes & dissent", "council_votes_maui.html"), ("Meeting minutes", "minutes_hi-maui.html")]),
 ("Entities & orgs", [("Organizations", "orgs_maui.html"), ("Connections", "connections_maui.html"),
                      ("Hotel & Lodging Assoc PAC", "entity_maui_hotel_lodging_assoc_pac.html"),
                      ("Maui Land & Pineapple PAC", "entity_maui_land_pineapple_co_inc_state_pac.html")]),
 ("Charter & law", [("Charter ↔ law crosswalk", "crosswalk_maui.html")]),
 ("Audit & oversight", [("Audit balance", "audit_balance.html"), ("govOS audit", "govos_audit_hi-maui.html"),
                        ("Oversight", "oversight_hi-maui.html")]),
 ("Maps", [("Parcel / TMK map", "maui_parcel_map.html")]),
]

# NOTE: no ".govos nav / .brand / .tenants / .chip" rules — page_html() emits NO <nav>. The caller
# (build_site.py's inject_nav) supplies the one standing govOS nav bar. Two navs on one page is the
# exact collision that made tenant_pages.py's output unreadable (2026-07-09 heal-audit finding).
CSS = """
.govos{--bg:#081420;--panel:#0f2540;--line:#1f3d5f;--ink:#eaf2fc;--ink-dim:#a7c0dd;--ink-faint:#6d89ab;
--blue:#2f74d0;--blue-2:#5a97e6;--blue-deep:#00356b;--gold:#e3ad33;--ok:#4bbf7b;
--glass-bg:rgba(22,50,78,0.55);--glass-line:rgba(90,151,230,0.24);
--glass-shadow:0 10px 34px -12px rgba(0,0,0,.6),0 1px 0 rgba(255,255,255,.05) inset;
--sans:-apple-system,"SF Pro Text","Segoe UI Variable Text","Segoe UI",system-ui,Roboto,sans-serif;
--mono:ui-monospace,"SF Mono",Menlo,"JetBrains Mono",Consolas,monospace;
min-height:100vh;margin:0;color:var(--ink);font-family:var(--sans);-webkit-font-smoothing:antialiased;line-height:1.5;
background:radial-gradient(1200px 620px at 14% -10%,rgba(47,116,208,.16),transparent 60%),
radial-gradient(900px 520px at 104% -4%,rgba(0,53,107,.55),transparent 55%),var(--bg);background-attachment:fixed}
.govos *{box-sizing:border-box}.govos .mono{font-family:var(--mono);font-variant-numeric:tabular-nums}
.govos .wrap{max-width:1060px;margin:0 auto;padding:18px 18px 64px}
.govos .btn{font:inherit;font-size:14px;font-weight:600;color:var(--ink);text-decoration:none;display:inline-flex;
align-items:center;gap:8px;min-height:40px;padding:0 16px;border-radius:11px;border:1px solid var(--glass-line);
background:var(--glass-bg);box-shadow:var(--glass-shadow);-webkit-backdrop-filter:blur(14px) saturate(1.2);backdrop-filter:blur(14px) saturate(1.2);transition:.18s}
.govos .btn:hover{border-color:var(--blue-2);color:#fff;transform:translateY(-1px)}
.govos .btn.solid{background:linear-gradient(180deg,var(--blue),var(--blue-deep));border-color:var(--blue);color:#fff}
.govos .btn.gold{background:linear-gradient(180deg,var(--gold),#c99320);border-color:var(--gold);color:#231802}
.govos .hero{margin:26px 2px 24px}
.govos .eyebrow{font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:var(--blue-2);font-weight:700}
.govos h1{font-size:clamp(28px,6vw,44px);line-height:1.05;margin:10px 0 8px;letter-spacing:-.01em;text-wrap:balance}
.govos h1 .u{color:var(--blue-2)}
.govos .sub{color:var(--ink-dim);max-width:60ch;font-size:16px}
.govos .cta{display:flex;gap:11px;margin-top:20px;flex-wrap:wrap}
.govos .sec{margin:26px 0 6px}
.govos .sec h2{font-size:12px;letter-spacing:.13em;text-transform:uppercase;color:var(--gold);font-weight:700;
display:flex;align-items:center;gap:10px;margin:0 0 12px}
.govos .sec h2 .n{font:600 11px/1 var(--mono);color:var(--ink-faint);border:1px solid var(--line);border-radius:999px;padding:3px 9px}
.govos .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:11px}
.govos .tile{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:14px 16px;border-radius:13px;
border:1px solid var(--glass-line);background:var(--glass-bg);box-shadow:var(--glass-shadow);
-webkit-backdrop-filter:blur(13px) saturate(1.12);backdrop-filter:blur(13px) saturate(1.12);
color:var(--ink);text-decoration:none;font-size:14.5px;font-weight:500;transition:.16s}
.govos .tile:hover{border-color:var(--blue-2);transform:translateY(-2px);color:#fff}
.govos .tile .go{color:var(--blue-2);font-size:13px;opacity:.7;transition:.16s}
.govos .tile:hover .go{opacity:1;transform:translateX(2px)}
.govos .foot{margin-top:30px;color:var(--ink-faint);font-size:12.5px;border-top:1px solid var(--line);padding-top:18px;
display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.govos .pill{display:inline-flex;align-items:center;gap:6px;font-size:12px;padding:4px 9px;border-radius:999px;border:1px solid var(--line);color:var(--ink-dim)}
.govos .dot{width:7px;height:7px;border-radius:50%}
@media(prefers-reduced-motion:reduce){.govos *{transition:none!important}}
"""


def page_html(sections, title="Maui County — every page | govOS",
             h1_plain="Maui County — ", h1_accent="every page",
             sub=("The full Maui tenant directory, grouped. Sourced from the public record, "
                  "cross-checked, laid side by side — patterns are questions, never accusations."),
             profile_html="", profile_css=""):
    """sections: list of (group_title, [(label, href), ...]) — ALREADY FILTERED to real pages by the
    caller. profile_html (2026-07-09, "rethought with the new audit profiles"): an optional pre-rendered
    block (from tenant_depth.profile_cards_html) inserted between the hero and the page grid, so the
    audit-profile scorecard leads the directory instead of a flat tile list starting the page. Returns a
    full HTML doc (<head>+<body class="govos">) with NO <nav> — the caller injects the one standing govOS
    nav bar. Pure function: no filesystem I/O, safe to call from anywhere."""
    total = sum(len(tiles) for _, tiles in sections)
    secs = []
    for gtitle, tiles in sections:
        cards = "".join('<a class="tile" href="%s"><span>%s</span><span class="go">&rarr;</span></a>'
                        % (esc(h), esc(n)) for n, h in tiles)
        secs.append('<section class="sec"><h2>%s <span class="n">%d</span></h2>'
                    '<div class="grid">%s</div></section>' % (esc(gtitle), len(tiles), cards))
    directory_head = ('<div class="sec" style="margin-top:0"><h2 style="margin-bottom:0">Every page</h2></div>'
                      if profile_html else "")
    return ('<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width,initial-scale=1">'
            '<title>%s</title><style>%s%s</style></head>'
            '<body class="govos"><div class="wrap">'
            '<div class="hero"><div class="eyebrow">Kilo Aupuni &middot; public record</div>'
            '<h1>%s<span class="u">%s</span></h1>'
            '<p class="sub">%s</p>'
            '<div class="cta"><a class="btn solid" href="maui_parcel_map.html">&#9656; Explore the map</a>'
            '<a class="btn" href="contracts_x_donors.html">&#9671; Money &times; votes</a>'
            '<a class="btn gold" href="audit_balance.html">&#9878; Audit balance</a></div></div>'
            '%s%s%s'
            '<div class="foot"><span class="pill"><span class="dot" style="background:var(--ok)"></span> all figures sourced (%d pages)</span>'
            '<span>govOS &middot; fresh Yale blue register &middot; sourced-only &middot; de-identified &middot; never libel</span></div>'
            '</div></body></html>') % (esc(title), CSS, profile_css, esc(h1_plain), esc(h1_accent), esc(sub),
                                       profile_html, directory_head, "".join(secs), total)


def build():
    """Standalone/ad-hoc refresh of reports/mauios/maui.html ONLY (a private civic-reports copy).
    Does NOT touch the published site/maui.html or king-local — those are owned by build_site.py's
    build_maui_nav_page(), which imports page_html() from this module. See module docstring."""
    page = page_html(SECTIONS)
    os.makedirs(OUT, exist_ok=True)
    outp = os.path.join(OUT, "maui.html")
    open(outp, "w", encoding="utf-8", newline="").write(page)
    print("built %s (%d bytes) — private ad-hoc copy only; published page is owned by "
          "12sgi-king/build_site.py's build_maui_nav_page()" % (outp, len(page)))


if __name__ == "__main__":
    build()
