#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""wp_branch_pages.py — generate WordPress-ready branch "working space" pages per tenant.

Mirrors the existing Hawaii County pattern (Council / Counsel / Executive / Judicial) with real,
already-sourced civic data for a given tenant -- no fabricated content, only links into reports
already generated by the govOS watchers (reports/mauios/*.html, published flat at 12sgi.com/*.html
per build_site.py). Each branch page links ONLY to resources that already exist on disk at
generation time, so a missing/renamed report can never produce a dead link.

Output (repo blueprint of record, like deploy_elementlotus_wp.py's element_lotus bundle):
  content/wordpress/branch_pages/<tenant>/
    - council.html
    - counsel.html
    - executive.html
    - judicial.html
    - manifest.json

Run:
  python watchers/wp_branch_pages.py --tenant maui --all
  python watchers/wp_branch_pages.py --tenant maui --branch council
"""
from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
MAUIOS = os.path.join(PROJ, "reports", "mauios")
OUT_ROOT = os.path.join(PROJ, "content", "wordpress", "branch_pages")
STATIC_BRIDGE = "https://12sgi.com/"
HST = timezone(timedelta(hours=-10))

# Tenant display names + naming convention matching the existing Hawaii County pages.
TENANTS = {
    "maui": "Maui County",
    "hawaii": "Hawai\u2018i County",
    "honolulu": "Honolulu",
    "kauai": "Kaua\u02bbi County",
    "state": "State of Hawai\u02bbi",
    "nyc": "New York",
}

BRANCH_TITLES = {
    "council":   "Council \u2014 Working Space",
    "counsel":   "Counsel \u2014 Case Review",
    "executive": "Executive / Administration \u2014 Working Space",
    "judicial":  "Judicial / Independent \u2014 Working Space",
}

BRANCH_INTRO = {
    "council": (
        "The legislative record for this county: meeting agendas, votes, minutes, and testimony. "
        "This workspace pulls the county council's own public record so members and staff can "
        "review what is scheduled, what was decided, and what the public said about it -- the "
        "record leads, the frame follows."
    ),
    "counsel": (
        "Legal and compliance review for this county: contracts crossed against campaign donors, "
        "entity dossiers on organizations doing business with or lobbying the county, sole-source "
        "and subcontract flags. Framed as civic questions for review, never as findings of "
        "wrongdoing -- every figure links back to its primary source."
    ),
    "executive": (
        "The administrative departments that run day-to-day county government: budget and "
        "finance, planning, public works, housing, and the other operating departments. This "
        "workspace is the executive branch's own dashboard into money, contracts, and department "
        "activity."
    ),
    "judicial": (
        "Independent oversight for this county: public-records requests, accountability and audit "
        "records, and the compliance-parity checks that hold every branch to the same public "
        "record standard. County government does not run its own courts (Hawai\u02bbi's circuit and "
        "district courts are state judiciary), so this workspace focuses on the county's own "
        "independent oversight bodies and mechanisms."
    ),
}

# capability -> (label, [(display_name, mauios_filename_without_ext_or_with_dir), ...])
# Every filename here is checked to exist on disk before being included -- no dead links.
BRANCH_RESOURCES = {
    "maui": {
        "council": [
            ("Meetings & agendas", [
                ("Council agendas", "agendas_maui.html"),
                ("Meetings calendar", "meetings_maui.html"),
                ("Meeting minutes", "minutes_hi-maui.html"),
                ("Council department", "dept_council_maui.html"),
            ]),
            ("Votes & testimony", [
                ("Council votes", "council_votes_maui.html"),
                ("Testimony tracker", "testifiers_maui.html"),
                ("Testimony record", "testimony_record.html"),
                ("Testimony \u00d7 money", "testimony_money.html"),
                ("Testimony effect map", "testimony_effect_map.html"),
            ]),
            ("Sunshine & members", [
                ("Open-meetings compliance", "sunshine_maui.html"),
                ("Member audit", "rep_audit.html"),
            ]),
        ],
        "counsel": [
            ("Contracts & compliance", [
                ("Contracts \u00d7 donors crossref", "contracts_x_donors.html"),
                ("Contract awards", "maui_contract_awards.html"),
                ("Sole-source watch", "sole_source_watch.html"),
                ("Subcontracts", "subcontracts_maui.html"),
                ("Oversight record", "oversight_hi-maui.html"),
                ("Corporation Counsel dept", "dept_corp_counsel_maui.html"),
                ("Prosecuting Attorney dept", "dept_prosecutor_maui.html"),
            ]),
            ("Entity dossiers", [
                ("L\u0101na\u02bbi Resorts LLC", "entity_lanai_resorts_llc.html"),
                ("Wailea Resort Development LP", "entity_wailea_resort_development_lp.html"),
                ("Maui Land & Pineapple Co.", "entity_maui_land_pineapple_co_inc_state_pac.html"),
                ("Maui Hotel & Lodging Assoc. PAC", "entity_maui_hotel_lodging_assoc_pac.html"),
                ("Bower Development LLC", "entity_bower_development_llc.html"),
                ("All entity dossiers", "entity_index.html"),
            ]),
        ],
        "executive": [
            ("Money & budget", [
                ("Campaign money", "money_maui.html"),
                ("Money chain", "money_chain_maui.html"),
                ("Money behind officials", "money_behind_officials.html"),
                ("Donor bloc", "donor_bloc.html"),
            ]),
            ("Departments", [
                ("All departments", "departments_maui.html"),
                ("Mayor", "dept_mayor_maui.html"),
                ("Finance", "dept_finance_maui.html"),
                ("Management", "dept_management_maui.html"),
                ("Planning", "dept_planning_maui.html"),
                ("Housing", "dept_housing_maui.html"),
                ("Public Works", "dept_public_works_maui.html"),
                ("Water", "dept_water_maui.html"),
                ("Transportation", "dept_transportation_maui.html"),
                ("Parks & Recreation", "dept_parks_maui.html"),
                ("Fire & Public Safety", "dept_fire_maui.html"),
                ("Police", "dept_police_maui.html"),
                ("Liquor Control", "dept_liquor_maui.html"),
                ("Environmental Management", "dept_environmental_maui.html"),
                ("Agriculture", "dept_agriculture_maui.html"),
                ("Personnel", "dept_personnel_maui.html"),
            ]),
            ("Land & recovery", [
                ("Parcel map", "maui_parcel_map.html"),
                ("Real estate", "realestate_maui.html"),
                ("Wildfire recovery watch", "wildfire_recovery_watch.html"),
            ]),
        ],
        "judicial": [
            ("Independent oversight", [
                ("Oversight record", "oversight_hi-maui.html"),
                ("Oversight help / how to use", "oversight_help.html"),
                ("Accountability record", "accountability_record.html"),
                ("Parity check", "parity_check.html"),
            ]),
            ("Public records", [
                ("Request records", "request_records.html"),
                ("govOS audit \u2014 Maui County", "govos_audit_hi-maui.html"),
            ]),
        ],
    },
}

CSS = """
 .wpbw{max-width:880px;margin:0 auto;font-family:Georgia,'Iowan Old Style',serif;line-height:1.55;color:#1c1c1c}
 .wpbw .eyebrow{font-family:Consolas,monospace;font-size:11px;letter-spacing:1.2px;color:#8a6d1f;text-transform:uppercase}
 .wpbw h2.wpbw-sec{font-family:Consolas,monospace;font-size:11px;letter-spacing:1.5px;text-transform:uppercase;color:#8a6d1f;border-bottom:1px solid rgba(0,0,0,.12);padding-bottom:6px;margin:24px 0 10px}
 .wpbw .lead{font-size:14px;color:#3a3a3a;max-width:80ch}
 .wpbw .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px;margin:8px 0 4px}
 .wpbw .card{border:1px solid rgba(0,0,0,.12);border-radius:10px;padding:10px 13px;background:rgba(0,0,0,.015)}
 .wpbw .card a{font-weight:600;text-decoration:none;color:#0a5a8a}
 .wpbw .card a:hover{text-decoration:underline}
 .wpbw .note{font-size:12px;color:#6a6a6a;font-style:italic;border-left:2px solid rgba(138,109,31,.5);padding:7px 12px;margin:16px 0}
 .wpbw footer.wpbw-foot{margin-top:26px;border-top:1px solid rgba(0,0,0,.1);padding-top:10px;font-family:Consolas,monospace;font-size:10.5px;color:#6a6a6a}
"""


def _existing_resources(tenant: str, branch: str) -> list[tuple[str, list[tuple[str, str]]]]:
    """Filter BRANCH_RESOURCES down to files that actually exist on disk right now."""
    groups = BRANCH_RESOURCES.get(tenant, {}).get(branch, [])
    out = []
    for group_label, items in groups:
        kept = [(label, fname) for label, fname in items
                if os.path.exists(os.path.join(MAUIOS, fname))]
        if kept:
            out.append((group_label, kept))
    return out


def build_page_html(tenant: str, branch: str) -> dict:
    tenant_name = TENANTS.get(tenant, tenant.title())
    branch_title = BRANCH_TITLES[branch]
    title = "%s \u2014 %s" % (tenant_name, branch_title)
    intro = BRANCH_INTRO[branch]
    groups = _existing_resources(tenant, branch)

    sections_html = ""
    resource_count = 0
    for group_label, items in groups:
        cards = ""
        for label, fname in items:
            url = STATIC_BRIDGE + fname
            cards += "<div class='card'><a href='%s' target='_blank' rel='noopener'>%s &#8599;</a></div>" % (url, label)
            resource_count += 1
        sections_html += "<h2 class='wpbw-sec'>%s</h2><div class='grid'>%s</div>" % (group_label, cards)

    if not groups:
        sections_html = (
            "<div class='note'>No sourced reports are on disk for this branch yet -- this page "
            "will fill in automatically as govOS watchers publish new %s data. Nothing is "
            "fabricated here; an empty section means the record isn't built yet, not that it "
            "doesn't exist.</div>" % tenant_name
        )

    ts = datetime.now(HST).strftime("%Y-%m-%d %H:%M HST")
    fragment = (
        "<!-- wp:group {\"tagName\":\"div\",\"className\":\"wpbw-wrap\"} -->\n"
        "<div class=\"wpbw-wrap\">\n"
        "<style>%s</style>\n"
        "<div class=\"wpbw\">\n"
        "<div class='eyebrow'>govOS \u00b7 %s \u00b7 private working space</div>\n"
        "<p class='lead'>%s</p>\n"
        "%s\n"
        "<div class='note'>Access is restricted to the %s Group in WordPress -- if you can read "
        "this, your access is already correctly scoped. Every link points to a report already "
        "generated from public primary sources; nothing on this page is fabricated or "
        "AI-summarized without a source link.</div>\n"
        "<footer class='wpbw-foot'>generated %s \u00b7 wp_branch_pages.py \u00b7 %d linked resources "
        "\u00b7 govOS / Kilo Aupuni</footer>\n"
        "</div>\n</div>\n"
        "<!-- /wp:group -->\n"
    ) % (CSS, tenant_name, intro, sections_html, branch, ts, resource_count)

    return {"title": title, "branch": branch, "tenant": tenant, "fragment": fragment,
            "resource_count": resource_count}


def build(tenant: str, branches: list[str] | None = None) -> dict:
    branches = branches or list(BRANCH_TITLES.keys())
    out_dir = os.path.join(OUT_ROOT, tenant)
    os.makedirs(out_dir, exist_ok=True)
    manifest = {"tenant": tenant, "tenant_name": TENANTS.get(tenant, tenant.title()), "pages": []}
    for branch in branches:
        built = build_page_html(tenant, branch)
        out_file = os.path.join(out_dir, "%s.html" % branch)
        with open(out_file, "w", encoding="utf-8", newline="\n") as f:
            f.write(built["fragment"])
        manifest["pages"].append({
            "branch": branch,
            "title": built["title"],
            "output": "%s.html" % branch,
            "resource_count": built["resource_count"],
        })
        print("wp_branch_pages: built %-9s -> %s  (%d resources)" % (
            branch, out_file, built["resource_count"]))
    manifest_path = os.path.join(out_dir, "manifest.json")
    with open(manifest_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
        f.write("\n")
    return manifest


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tenant", required=True, choices=list(TENANTS.keys()))
    ap.add_argument("--branch", choices=list(BRANCH_TITLES.keys()), default=None)
    ap.add_argument("--all", action="store_true", help="build all 4 branch pages for --tenant")
    a = ap.parse_args()
    if not a.all and not a.branch:
        raise SystemExit("pass --all or --branch <council|counsel|executive|judicial>")
    branches = [a.branch] if a.branch else None
    manifest = build(a.tenant, branches)
    print("wp_branch_pages: %d page(s) built for %s" % (len(manifest["pages"]), manifest["tenant_name"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
